---
gems:
  - jekyll-redirect-from

defaults:
  - scope:
      path: ''
    values:
      layout: default

  - scope:
      type: posts
      path: news
    values:
      layout: news

permalink: pretty
# baseurl: https://wdaqua.github.io

collections:
  students:
    output: true
  supervisors:
    output: true
  advisors:
    output: true
  events:
    output: false
