---
defaults:
  - scope:
      path: ''
    values:
      layout: default

  - scope:
      type: posts
      path: blog
    values:
      layout: blost

permalink: pretty
# baseurl: https://wdaqua.github.io

collections:
  students:
    output: true
